Repository health-connector/gluedb, pull requests merged in 2019-05, with the labels that each got.

#103 40872
  app/data_migrations/change_policy_employer.rb
  lib/tasks/change_policy_employer.rake
  spec/data_migrations/change_policy_employer_spec.rb
Labels: Priority: High, Status: Accepted Pending Release, Tracker: Trading Partner Data

#108 22668
  .overcommit.yml
  app/models/external_events/external_policy_member_drop.rb
  spec/models/external_events/external_policy_member_drop_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#109 40696
  app/models/employer_events/renderer.rb
  spec/models/employer_events/renderer_spec.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Critical Data
